name:                "drasil-artifacts"
version:             0.1.0.0
github:              "balacij/drasil-artifacts"
license:             "Yes"
author:              "Jason Balaci"
maintainer:          "jason@balaci.me"
copyright:           "2024 Jason Balaci"
language: GHC2021
extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/drasil-artifacts#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- pretty
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-export-lists

library:
  source-dirs: src

executables:
  drasil-artifacts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - drasil-artifacts

tests:
  drasil-artifacts-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - drasil-artifacts
